### ISSUE TITLE
Stealing Partial Exclusivity

### ISSUE THREAD

**Issue by Hexaiter** [univrsal/input-overlay#368]
**Describe the bug**
Input overlay is stealing partial exclusivity over the controllers. And by that, it means that there are a few programs that stop being able to read controller input while others do not. And one of them are window's built in Game Controllers control panel. Other programs that are affected are JoyToKey, as well as AutoHotKey.

**To Reproduce**
- Launch OBS, make sure Input Overlay is setup for the specific controller.
- Open `Set up USB Game Controllers` control panel.
- See input on controller not being read by it's `Properties` window.
- Close OBS and see the Properties window is now able to see inputs.
 
 
**Expected behavior**
Game Controllers control panel, as well as any other program, should still be able to read inputs.

**~~Media Examples~~**
I would record a video demonstrating how control is restored as soon as OBS is closed, but since I use OBS to record video that poses a problem.
 
 
**Additional information:**
- input-overlay v5.0.4
- Full OBS Studio log https://obsproject.com/logs/nodcTVxrtMeq9P9n

I used my 8bitdo SN30 controller to test against different controller protocols.
The good: Input Overlay will not steal input for dInput nor xInput mode
The bad: Input Overlay WILL steal if it is in Switch mode. 
Then confirmed with an <ins>actual</ins> Switch Pro Controller.

Gamepad input stealing thankfully doesn't occur to the majority of programs/games from what I've seen. But the ones it does are useful tools, whether it's diagnostic, such as Window's own old built in configuration tool, to input management programs such as AutoHotKey.

** **
<ins>**Workaround Found**</ins>
I have found a way to regain control while still letting the Overlay plugin work. And it is a bit convoluted.

- Run intended program that is meant to have input that Input Overlay is stealing from.
- Run a program or game that will steal total input control. Such as anything that uses Steam Input, including Steam itself. But I've found Timespinner works well because it will very annoyingly force steam input on even if you have it disabled.
- Run OBS   :   Note OBS and the Input Stealing program launch order between the two do not matter.
- Close the known input stealing program.
- Now the intended program is able to read input while OBS displays the Input Overlay working.

Recording of the workaround working, using https://gamepadviewer.com/ via capture window of firefox for showing the input being stolen by Input Overlay till Timespinner was opened then closed.

https://github.com/univrsal/input-overlay/assets/145405634/1ba041d3-37a0-4d89-9019-05e022cbc76c

It's a bit of a fortuitous moment just accidentally coming across the workaround. I occasionally stream the Timespinner randomizer, so I've ran into it's problems before. And have had to use HidHide to get things like Push to Talk to work while it's running, since it completely ignores your Disable Steam Input setting. Which might be part of why the workaround works since Steam Input has been known to steal input in general unless you disable it... usually. Playing Timespinner being an exception.

And it just so occurred a moment while setting something else up that, when I closed Timespinner, I noticed that JoyToKey regained access to reading inputs.
Also it looks like when launching Steam it'll initialize Steam Input then stop it and that may be enough for Input Overlay to stop it's stealing from other opened programs.

**End Notes**

I hope this issue report is not too jumbled. While I was writing it I kept finding additional information of what was going on and updated as I could.

**Comment by univrsal** [comment]
This is probably more an issue with sdl2 than with input overlay as that's the library used for gamepad input. The plugin [uses some hints](https://github.com/univrsal/input-overlay/blob/master/src/hook/gamepad_hook_helper.cpp#L30-L39) to tell sdl2 how to configure gamepad input, but that's about it.

**Comment by PhenaOfMari** [comment]
Hey there, I found this issue a little while ago and just wanted to say I've just submitted a [PR to SDL](https://github.com/libsdl-org/SDL/pull/9821) that should fix this issue when it lands in a release.

**Comment by univrsal** [comment]
I have updated the windows version of sdl to 2.30.4, so I assume this should be fixed now(?)

**Comment by PhenaOfMari** [comment]
I'm not sure if Windows was affected by this in any way. As I understand it, Linux (or at least Arch) links to the SDL installed by the distro repositories. That being said, my fix did get into 2.30.4 and I can confirm that at least in my use case it works properly on Arch now. Hopefully its good for everyone else, too!

**Comment by univrsal** [comment]
Well the original issue report was for windows, so I guess then the original bug still exists then.

**Comment by PhenaOfMari** [comment]
Oh I see that now, I must have glossed over that when reading it in the past. I think it should be fixed since you updated the library, but I wouldn't be able to confirm it for you myself.

**Comment by Hexaiter** [comment]
Sorry for the late response.
I had seen the notice back in July the change had been made and had been waiting for a release, not realizing that I should have grabbed the new dll from the deps to test. But after now just seeing the emails of Phena's messages, I came to that conclusion.

The long story short, it appears to be working just fine now with it. No longer having the issue from what I can see. It is no longer stealing exclusivity thanks to it.

I do not know if you want to just close the issue now, since it'll be resolved in the next version, or wait till the next version is out, so I'll leave it up for you.

**Comment by PhenaOfMari** [comment]
Great! Glad I could get this fixed.

**Comment by univrsal** [comment]
I'll just make a new release now.
