### ISSUE TITLE
Input flickering

### ISSUE THREAD

**Issue by Voxelse** [univrsal/input-overlay#65]
Sometimes the visual inputs just stop working and so the inputs are flickering.
It's not a controller issue so I used an other input display (from web) to see if it was flickering too.
Top input display is yours and bottom is the web one (yours is flickering but not the bottom one).

![inputflicker](https://user-images.githubusercontent.com/11724596/49695606-eb3ed180-fb9d-11e8-96c1-532fd2d0b405.gif)

Any idea on how to fix that?
Thanks.

**Comment by univrsal** [comment]
I can't reproduce it with my preset and gamepad. Can you give me your preset, so I can see if that's the issue? It might also be that the test build of v5 I gave out has this issue, which I already fixed but haven't released yet.

I'll try and give you an updated test build, but it'll take a bit

**Comment by Voxelse** [comment]
Yeah sure.
[layout_flickering.zip](https://github.com/univrsal/input-overlay/files/2660978/layout_flickering.zip)
The version of the build is the one you gave here: https://github.com/univrsal/input-overlay/issues/55

Thanks for the help!

**Comment by univrsal** [comment]
For me to test this, I'd also need the texture, not just the config file :P.
Anyways, I have a current test build, so you can test if the issue still occurs:
[input-overlay v5-pre2.zip](https://github.com/univrsal/input-overlay/files/2662840/input-overlay.v5-pre2.zip)

**Comment by Voxelse** [comment]
Oh yeah sorry I'm dumb :x.
I've tested it with your build but it didn't fix it :/.
Here is my config + texture files : [presets.zip](https://github.com/univrsal/input-overlay/files/2662964/presets.zip)

**Comment by univrsal** [comment]
Well it seems like the issue is the input processing.
There's two different threads, one processes gamepad input and one that takes the input and draws the overlay based on the input. While the one process gathers the gamepad input the other process cannot access the data to draw the overlay, which means all buttons are set to unpressed.

I guess I'll have to come up with a better solution to this

**Comment by univrsal** [comment]
Alright, I fixed the issue. The input data is now separately stored for each overlay, which makes sure that the overlay always has data to display. I don't know when I'll give out a new build though
